services:
  ubuntu:
    image: ghcr.io/pycabbage/ubuntu-full-docker:latest
    pull_policy: always
    build:
      context: .
      target: final
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: ["bash", "-c", "while :; do sleep 3600; done"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
