services:
  ubuntu2204: &ubuntu2204
    image: ghcr.io/pycabbage/ubuntu-full-docker:22.04
    pull_policy: always
    build: &ubuntu2204_build
      context: .
      target: final
      args:
        - VARIANT=22.04
        - &ubuntu_args_nonroot_user NONROOT_USER=ubuntu
        - &ubuntu_args_python_version PYTHON_VERSION=3.12.3
        - &ubuntu_args_nodejs_version NODEJS_VERSION=v22.1.0
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: ["bash", "-c", "while :; do sleep 3600; done"]
    volumes:
      - &ubuntu_volume_apt_cache apt-cache:/var/cache/apt
      - &ubuntu_volume_apt_store apt-store:/var/lib/apt
      - &ubuntu_volume_docker_sock /var/run/docker.sock:/var/run/docker.sock
      - &ubuntu_volume_docker_cache docker-cache:/var/lib/docker
    group_add:
      - docker
  ubuntu2404: &ubuntu2404
    <<: *ubuntu2204
    image: ghcr.io/pycabbage/ubuntu-full-docker:24.04
    build:
      <<: *ubuntu2204_build
      args:
        - VARIANT=24.04
        - *ubuntu_args_nonroot_user
        - *ubuntu_args_python_version
        - *ubuntu_args_nodejs_version
  test2204:
    <<: *ubuntu2204
    volumes: &test_volumes
      - *ubuntu_volume_apt_cache
      - *ubuntu_volume_apt_store
      - *ubuntu_volume_docker_sock
      - *ubuntu_volume_docker_cache
      - ./scripts/:/tmp/scripts/
    command: &test_command ["bash", "/tmp/scripts/test.sh"]

  test2404:
    <<: *ubuntu2404
    volumes: *test_volumes
    command: *test_command

volumes:
  apt-cache:
  apt-store:
  docker-cache:
