services:
  ubuntu:
    image: ghcr.io/pycabbage/ubuntu-full-docker:24.04
    pull_policy: always
    build:
      context: .
      target: final
      args:
        - VARIANT=24.04
        - NONROOT_USER=ubuntu
        - PYTHON_VERSION=3.12.3
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    command: ["bash", "-c", "while :; do sleep 3600; done"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - apt-cache:/var/cache/apt
      - apt-store:/var/lib/apt
      - docker-cache:/var/lib/docker
    group_add:
      - docker

volumes:
  apt-cache:
  apt-store:
  docker-cache:
